### ISSUE TITLE
Unable to build on MacOS (intel)

### ISSUE THREAD

**Issue by kylekrny** [Leagueify/leagueify#164]
**Describe the bug**
Due to an issue with vite and "@esbuild" packaging pulling an darwin version instead of linux version.

**To Reproduce**

1. Buy a good computer
2. try to run the sandbox environment on said good computer
3. realize the creator of this is prejudice against the superior race of computers

**Expected behavior**
Should be able to dev, and I cannot dev.

**Screenshots**
Mr duBois saw this debacle happen. 

**Desktop (please complete the following information):**

- OS: MacOS
- Browser n/a
- Version 0.40

**Comment by MichaelCduBois** [comment]
Closing this as #171 has taken over this issue, due to the new tech stack.
