### ISSUE TITLE
Identify Style Library or Framework

### ISSUE THREAD

**Issue by MichaelCduBois** [Leagueify/leagueify#200]
We should identify what we are going to use syling.

**Comment by kylekrny** [comment]
There are really 2 options
- [Tailwind UI / Tailwind CSS](https://tailwindcss.com/)
   - Great standard dashboard layout to help with ease of getting things setup
   - great component library, while not giving you the kitchen sink as well
   - Not as popular as bootstrap but still used a lot and very robust network 
- [Bootstrap](https://getbootstrap.com/)
    - great for ease of use (most used framework, don't need to reference API docs)
    - great for library of components / classes (they have quite the library of components)
    - Size of package (The size of bootstrap is really rather large and gives you too much that we don't need)
    - Bootstrap vesions can be a bit of a pain and working with Reactstrap can break things


There are other options to consider but they aren't as popular or as user-firendly
- [Material UI](https://mui.com/)
- [Semantic](https://semantic-ui.com/)

**Comment by kylekrny** [comment]
@MichaelCduBois ^^

**Comment by kylekrny** [comment]
Will get tailwind installed tomorrow if you agree.

**Comment by MichaelCduBois** [comment]
Tailwind works for me, I have seen others discuss and implement Tailwind. I have wanted to for a while, but never got around to doing so.
